3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Models/Certame.cs
using System.ComponentModel.DataAnnotations;

namespace Feira_Facil.Models
{
    public class Certame
    {

        [Key]
        public int IdCertame { get; set; }
        public int maxStandsCertame { get; set; }
        public string categoraCertame { get; set; }
        public int ativo { get; set; }

    }
}

3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Controllers/CertamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Feira_Facil.Data;
using Feira_Facil.Models;
using System.Configuration;
using NuGet.Packaging;
using System.Collections.Specialized;

namespace Feira_Facil.Controllers
{
    public class CertamesController : Controller
    {
        private readonly Feira_FacilContext _context;

        public CertamesController(Feira_FacilContext context)
        {
            _context = context;
        }

        // GET: Certames
        public async Task<IActionResult> Index()
        {
            var ret = await _context.Certame.Where(c => c.ativo == 1).ToListAsync();
            var contaStands = new Dictionary<int, int>();

			foreach (Certame c in ret)
            {
                contaStands.Add(c.IdCertame, _context.Stand.Where(s => s.idCertame == c.IdCertame).Count());
            }

            ViewBag.contaStands = contaStands;
            return View(ret);
        }

		public async Task<IActionResult> Ver(int? id)
		{
			if (id == null || _context.Certame == null)
			{
				return NotFound();
			}

            var stands = await _context.Stand.Where(s => s.idCertame == id).ToListAsync();
            var produtos = new List<String>();
            ViewBag.Produtos = (await _context.Produto.
                                Join(_context.Vendedor, p => p.idVendedor,
                                v => v.Id, (p, v) => new { p, v })
                                .Join(_context.Stand, s => s.p.idStand,
                                c => c.IdStand, (s,c) => new { nome = s.p.nome, nome_vendedor = s.v.nome, id_stand = s.p.idStand, id_certame = c.idCertame, imagens = s.p.imagens }).Where(z => z.id_certame == id)
                                .ToListAsync());



            return View();
		}

		// GET: Certames/Details/5
		public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Certame == null)
            {
                return NotFound();
            }

            var certame = await _context.Certame
                .FirstOrDefaultAsync(m => m.IdCertame == id);
            if (certame == null)
            {
                return NotFound();
            }

            return View(certame);
        }

        // GET: Certames/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Certames/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCertame,maxStandsCertame,categoraCertame")] Certame certame)
        {
            if (ModelState.IsValid)
            {
                _context.Add(certame);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(certame);
        }

        // GET: Certames/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Certame == null)
            {
                return NotFound();
            }

            var certame = await _context.Certame.FindAsync(id);
            if (certame == null)
            {
                return NotFound();
            }
            return View(certame);
        }

        // POST: Certames/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCertame,maxStandsCertame,categoraCertame")] Certame certame)
        {
            if (id != certame.IdCertame)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(certame);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CertameExists(certame.IdCertame))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(certame);
        }

        // GET: Certames/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Certame == null)
            {
                return NotFound();
            }

            var certame = await _context.Certame
                .FirstOrDefaultAsync(m => m.IdCertame == id);
            if (certame == null)
            {
                return NotFound();
            }

            return View(certame);
        }

        // POST: Certames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Certame == null)
            {
                return Problem("Entity set 'Feira_FacilContext.Certame'  is null.");
            }
            var certame = await _context.Certame.FindAsync(id);
            if (certame != null)
            {
                _context.Certame.Remove(certame);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CertameExists(int id)
        {
          return _context.Certame.Any(e => e.IdCertame == id);
        }
    }
}

3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Views/Certames/Create.cshtml
@model Feira_Facil.Models.Certame

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Certame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="maxStandsCertame" class="control-label"></label>
                <input asp-for="maxStandsCertame" class="form-control" />
                <span asp-validation-for="maxStandsCertame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoraCertame" class="control-label"></label>
                <input asp-for="categoraCertame" class="form-control" />
                <span asp-validation-for="categoraCertame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Views/Certames/Delete.cshtml
@model Feira_Facil.Models.Certame

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Certame</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.maxStandsCertame)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.maxStandsCertame)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categoraCertame)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categoraCertame)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdCertame" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Views/Certames/Edit.cshtml
@model Feira_Facil.Models.Certame

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Certame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdCertame" />
            <div class="form-group">
                <label asp-for="maxStandsCertame" class="control-label"></label>
                <input asp-for="maxStandsCertame" class="form-control" />
                <span asp-validation-for="maxStandsCertame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoraCertame" class="control-label"></label>
                <input asp-for="categoraCertame" class="form-control" />
                <span asp-validation-for="categoraCertame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Views/Certames/Index.cshtml
@{
	ViewData["Title"] = "Feiras";
}

<h1><center>Feiras disponíveis</center></h1>

@if (Model == null)
{
	<h1>Não há certames</h1>
	throw new Exception("Please use a specific Exception");

}

<div class="row">
	<div class="col-12">
		<table class="table table-image">
			<thead>
				<tr>
					<th scope="col">ID</th>
					<th scope="col">Categoria</th>
					<th scope="col">Nº Stands</th>
					<th scope="col">Assistir</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@item.IdCertame
						</td>
						<td>
							@item.categoraCertame
						</td>
						<td>
							@ViewBag.contaStands[item.IdCertame]
						</td>
						<td>
							<a href='@Url.Action("Ver", "Certames", new { id = item.IdCertame })'><button class="btn btn-primary">Aceder</button></a>
						</td>
					</tr>
				}
			</tbody>

		</table>
	</div>
</div>

3rd Year/1st Semester/Computer Labs IV/Project/LI4/Projeto/FeiraFacil_MVC/Feira Facil/Feira Facil/Views/Certames/Ver.cshtml

@{
    ViewData["Title"] = "Details";
}


<h1><center>Lista de Produtos nos Diversos Stands</center></h1>

<div>
    
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Vendedor</th>
                <th scope="col">Imagens</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Produtos)
            {
                <tr>
                    <td>@item.nome</td>
                    <td>@item.nome_vendedor</td>
                    <td>@item.imagens</td>
                    <td><a><button class="btn btn-success">Adicionar ao Carrinho</button></a></td>
                </tr>

            }
        </tbody>
    </table>
   
</div>